[package]
    authors       = ["François Mockers <francois.mockers@vleue.com>"]
    categories    = ["game-development"]
    description   = "Animated GIF player for Bevy"
    documentation = "https://docs.rs/vleue_kinetoscope"
    edition       = "2024"
    exclude       = ["animated-gif.webp", "assets/big-buck-bunny.webp"]
    homepage      = "https://github.com/vleue/vleue_kinetoscope"
    keywords      = ["animation", "bevy", "gif"]
    license       = "MIT OR Apache-2.0"
    name          = "vleue_kinetoscope"
    readme        = "README.md"
    repository    = "https://github.com/vleue/vleue_kinetoscope"
    version       = "0.5.0"

[features]
    default   = ["gif", "streaming", "webp"]
    gif       = ["image/gif"]
    streaming = ["bevy_tasks/multi_threaded"]
    webp      = ["image/webp"]

[dependencies]
    bevy_app          = { version = "0.18", default-features = false }
    bevy_asset        = { version = "0.18", default-features = false }
    bevy_ecs          = { version = "0.18", default-features = false }
    bevy_image        = { version = "0.18", default-features = false }
    bevy_reflect      = { version = "0.18", default-features = false }
    bevy_sprite       = { version = "0.18", default-features = false }
    bevy_tasks        = { version = "0.18", default-features = false, optional = true }
    bevy_time         = { version = "0.18", default-features = false }
    crossbeam-channel = "0.5"
    image             = { version = "0.25", default-features = false }
    log               = "0.4"
    smallvec          = "1.15"
    thiserror         = "1.0"


[dev-dependencies]
    bevy = { version = "0.18", default-features = false, features = ["bevy_log", "bevy_sprite", "bevy_ui", "bevy_window", "bevy_winit", "default_font", "x11"] }
